/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author caodi
 */
public class FormMain extends javax.swing.JFrame {

    /**
     * Creates new form FormMain
     */
    public FormMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jP = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuTrangChu = new javax.swing.JMenu();
        jMenuThongTin = new javax.swing.JMenuItem();
        jMenuThoat = new javax.swing.JMenuItem();
        jMenuQuanLy = new javax.swing.JMenu();
        jMenuQuanLyThongTin = new javax.swing.JMenuItem();
        jMenuQuanLyHangHoa = new javax.swing.JMenuItem();
        jMenuQuanLyHoaDon = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPLayout = new javax.swing.GroupLayout(jP);
        jP.setLayout(jPLayout);
        jPLayout.setHorizontalGroup(
            jPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 559, Short.MAX_VALUE)
        );
        jPLayout.setVerticalGroup(
            jPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 355, Short.MAX_VALUE)
        );

        jMenuTrangChu.setText("Trang chủ");

        jMenuThongTin.setText("Thông tin");
        jMenuTrangChu.add(jMenuThongTin);

        jMenuThoat.setText("Thoát");
        jMenuThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuThoatActionPerformed(evt);
            }
        });
        jMenuTrangChu.add(jMenuThoat);

        jMenuBar1.add(jMenuTrangChu);

        jMenuQuanLy.setText("Quản lý");

        jMenuQuanLyThongTin.setText("Quản lý thông tin");
        jMenuQuanLyThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuQuanLyThongTinActionPerformed(evt);
            }
        });
        jMenuQuanLy.add(jMenuQuanLyThongTin);

        jMenuQuanLyHangHoa.setText("Quản lý hàng hóa");
        jMenuQuanLy.add(jMenuQuanLyHangHoa);

        jMenuQuanLyHoaDon.setText("Quản lý hóa đơn");
        jMenuQuanLy.add(jMenuQuanLyHoaDon);

        jMenuBar1.add(jMenuQuanLy);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuQuanLyThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuQuanLyThongTinActionPerformed
        FormQLTT qltt = new FormQLTT();
        jP.add(qltt);
        qltt.setVisible(true);
    }//GEN-LAST:event_jMenuQuanLyThongTinActionPerformed

    private void jMenuThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuThoatActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jMenuThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuQuanLy;
    private javax.swing.JMenuItem jMenuQuanLyHangHoa;
    private javax.swing.JMenuItem jMenuQuanLyHoaDon;
    private javax.swing.JMenuItem jMenuQuanLyThongTin;
    private javax.swing.JMenuItem jMenuThoat;
    private javax.swing.JMenuItem jMenuThongTin;
    private javax.swing.JMenu jMenuTrangChu;
    private javax.swing.JPanel jP;
    // End of variables declaration//GEN-END:variables
}
